# PROPRIETARY LICENSE

**Copyright © 2025 Genesis Forge. All Rights Reserved.**

---

## PERSONAL USE LICENSE

### 1. GRANT OF LICENSE

Genesis Forge ("Licensor") grants you a non-exclusive, non-transferable, revocable license to use EduFocus Pro ("Software") for personal, non-commercial purposes only.

This license is granted free of charge for personal and educational use, subject to the terms and conditions set forth herein.

### 2. PERMITTED USES

You MAY:

* Install and use the Software on your personal devices
* Modify the Software for your own personal use only
* Create backups of your personal data generated by the Software
* Share the Software's official distribution link with others
* Use the Software for personal study, learning, and educational purposes
* Install the Software on multiple personal devices that you own or control

### 3. RESTRICTIONS

You may NOT:

* **Commercial Use:** Use the Software for commercial purposes without a separate commercial license
* **Distribution:** Sell, rent, lease, sublicense, or otherwise distribute the Software
* **Public Modifications:** Distribute modified versions of the Software publicly or make them available to third parties
* **Branding:** Remove, alter, or obscure copyright notices, trademarks, licenses, or proprietary notices
* **Derivative Branding:** Use the Software name, "EduFocus Pro," "Genesis Forge," or related branding for derivative works without explicit written permission
* **Reverse Engineering:** Reverse engineer, decompile, or disassemble the Software for competitive or commercial purposes
* **Circumvention:** Bypass, disable, or circumvent any security features or technical limitations
* **Illegal Use:** Use the Software in violation of applicable laws, regulations, or third-party rights
* **Unauthorized Access:** Attempt to gain unauthorized access to any systems, networks, or data
* **Redistribution:** Redistribute the Software through unofficial channels, package managers, or repositories
* **Repackaging:** Repackage or rebrand the Software without written authorization

### 4. EDUCATIONAL INSTITUTIONS

Schools, universities, colleges, libraries, and other educational institutions may use this Software free of charge for educational purposes, provided they:

* **Non-Commercial:** Do not charge students, staff, or faculty for access to the Software
* **Notification:** Notify Genesis Forge of institutional deployment at edufocusbusiness@gmail.com
* **Educational Use:** Use the Software solely for legitimate educational purposes
* **Best Practices:** Use the Software in accordance with educational best practices and applicable privacy laws (FERPA, GDPR, COPPA, etc.)
* **No Modification Distribution:** Do not distribute modified versions without permission

**Educational or personal use does NOT require a commercial license.**

### 5. COMMERCIAL USE

**Commercial use includes but is not limited to:**

* Selling access to the Software or its features
* Using the Software as part of a paid service, product, or offering
* Integrating the Software into commercial software products
* Using the Software for business training, corporate training, or consulting services
* Deploying the Software in for-profit organizations for employee productivity
* Offering Software-as-a-Service (SaaS) based on this Software
* Using the Software to generate revenue directly or indirectly
* Including the Software in commercial bundles or packages

**Any commercial use requires a separate commercial license from Genesis Forge.**

**For commercial licensing inquiries, contact:** edufocusbusiness@gmail.com  
**Subject:** Commercial License Inquiry

### 6. MODIFICATIONS AND DERIVATIVES

#### Personal Modifications

* You may modify the Software for your own personal use only
* Modified versions must retain all original copyright notices, trademarks, and this license in their entirety
* Personal modifications may not be distributed, shared, or made publicly available

#### Public Distribution Prohibited

* Public distribution of modified versions is strictly prohibited without explicit written permission from Genesis Forge
* "Public distribution" includes but is not limited to:
  - Posting on websites, repositories (GitHub, GitLab, etc.), or forums
  - Sharing via file-sharing services or cloud storage
  - Distributing to colleagues, classmates, or groups
  - Making available through package managers or app stores

#### Derivative Works

* Derivative works intended for any form of distribution require explicit written authorization from Genesis Forge
* Written authorization must be obtained by emailing edufocusbusiness@gmail.com
* Authorization requests should include:
  - Description of the derivative work
  - Intended use and distribution method
  - Target audience
  - Whether commercial or non-commercial

#### Contributing Back

* Contributing modifications back to the official repository is encouraged but not required
* Contributions must be submitted via official channels (email or designated repository)
* By contributing, you grant Genesis Forge perpetual, irrevocable rights to use, modify, and distribute your contributions
* Contributors will be credited in the project's acknowledgments (unless you prefer to remain anonymous)

### 7. DATA PRIVACY AND RESPONSIBILITY

#### Local Storage Only

* The Software stores all user data locally on the user's device using Chrome's local storage API
* No user data is transmitted to external servers, third parties, or Genesis Forge
* The Software operates entirely offline after initial installation

#### No Data Collection

* Genesis Forge has no access to, does not collect, transmit, or store any user data
* No analytics, telemetry, usage statistics, or personal information is collected
* No cookies, tracking pixels, or similar technologies are used

#### User Responsibility

* Users are solely responsible for backing up their own data using the Software's export functionality
* Genesis Forge is not responsible for data loss, corruption, or deletion resulting from:
  - User error
  - Device failure or loss
  - Browser updates or crashes
  - Software uninstallation or reinstallation
  - Operating system issues
  - Any other cause beyond Genesis Forge's control

#### Device Security

* Data security is dependent on the user's device security practices
* Users are responsible for:
  - Securing their devices with passwords/encryption
  - Maintaining up-to-date antivirus/security software
  - Protecting against unauthorized physical access
  - Following security best practices

#### Privacy Compliance

* The Software is designed to comply with GDPR, FERPA, COPPA, and other privacy regulations
* Compliance is achieved through zero data collection
* Users must ensure their own use complies with applicable privacy laws

### 8. ATTRIBUTION

When referencing, discussing, or promoting this Software publicly, please provide proper attribution:

**Required Attribution:**
* "EduFocus Pro by Genesis Forge"

**Optional Additional Attribution:**
* Link to official distribution source (Chrome Web Store)
* Version number being referenced
* "Privacy-First Education Technology"

**Attribution Requirements:**

* **Educational materials:** Include attribution when using in presentations, courses, or educational content
* **Blog posts/articles:** Provide attribution and link to official source
* **Social media:** Mention "EduFocus Pro by Genesis Forge" when sharing
* **Academic papers:** Cite appropriately according to your citation style

### 9. WARRANTY DISCLAIMER

**THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.**

Genesis Forge makes no warranties or guarantees regarding:

* **Fitness for Purpose:** The Software's suitability for any particular purpose or use case
* **Reliability:** Uninterrupted, error-free, or bug-free operation
* **Data Integrity:** Accuracy, completeness, or preservation of user data
* **Compatibility:** Compatibility with all systems, browsers, devices, or configurations
* **Performance:** Speed, efficiency, or resource usage
* **Security:** Complete security or protection against all threats
* **Updates:** Availability of future updates, bug fixes, or new features
* **Support:** Availability or quality of technical support
* **Results:** Any specific results, outcomes, or improvements in productivity or learning

**USE AT YOUR OWN RISK.**

You acknowledge that you are using the Software at your own risk and discretion.

### 10. LIMITATION OF LIABILITY

**IN NO EVENT SHALL GENESIS FORGE, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, OR LICENSORS BE LIABLE FOR ANY:**

* **Direct Damages:** Any direct loss, damage, or injury
* **Indirect Damages:** Incidental, consequential, special, exemplary, or punitive damages
* **Data Loss:** Loss, corruption, deletion, or unavailability of user data
* **Financial Loss:** Loss of profits, revenue, business opportunities, or savings
* **Academic Consequences:** Poor grades, failed courses, academic penalties, or missed deadlines
* **Professional Consequences:** Job loss, missed opportunities, or career setbacks
* **Device Damage:** Damage to hardware, software, or other property
* **Third-Party Claims:** Claims arising from third parties related to your use of the Software
* **Downtime:** Inability to use the Software due to bugs, updates, or discontinuation

**INCLUDING BUT NOT LIMITED TO DAMAGES ARISING FROM:**

* Software bugs, errors, or defects
* Data loss or corruption
* Security vulnerabilities or breaches
* Compatibility issues
* Performance problems
* User error or misuse
* Third-party interference
* Browser or operating system issues
* Internet connectivity problems
* Any other cause whatsoever

**REGARDLESS OF THE THEORY OF LIABILITY** (WHETHER IN CONTRACT, STRICT LIABILITY, TORT INCLUDING NEGLIGENCE, OR OTHERWISE) **ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.**

**Maximum Liability:** TO THE EXTENT LIABILITY CANNOT BE EXCLUDED BY LAW, GENESIS FORGE'S TOTAL LIABILITY SHALL NOT EXCEED FIFTY DOLLARS (USD \$50.00).

### 11. INDEMNIFICATION

You agree to indemnify, defend, and hold harmless Genesis Forge, its directors, officers, employees, affiliates, agents, contractors, licensors, and representatives from and against any and all claims, liabilities, damages, losses, costs, expenses, and fees (including reasonable attorneys' fees and court costs) arising from or relating to:

* **Your Use:** Your installation, access, or use of the Software
* **Your Misuse:** Your misuse, abuse, or improper use of the Software
* **Violation of Terms:** Your violation of this license or any applicable laws, regulations, or third-party rights
* **Your Content:** User data, content, or information you create, store, or manage using the Software
* **Your Modifications:** Any modifications you make to the Software
* **Third-Party Claims:** Claims by third parties arising from your actions
* **Data Loss:** Claims related to data loss affecting you or others
* **Intellectual Property:** Intellectual property infringement claims related to your use
* **Negligence:** Your negligent or intentional acts or omissions

**Cooperation:** You agree to cooperate fully with Genesis Forge in the defense of any indemnified claim and to provide all reasonably requested information and assistance.

**Control of Defense:** Genesis Forge reserves the right to assume exclusive defense and control of any matter subject to indemnification by you, at your expense.

### 12. TERMINATION

This license is effective upon your first use of the Software and continues until terminated.

#### Automatic Termination

Your rights under this license terminate automatically and immediately without notice from Genesis Forge if you:

* Fail to comply with any term or condition of this license
* Use the Software for commercial purposes without a commercial license
* Distribute modified versions publicly
* Violate intellectual property rights
* Engage in prohibited uses outlined in Section 3

#### Termination by Genesis Forge

Genesis Forge may terminate this license at any time, with or without cause, by providing notice through:

* Notification within the Software
* Email (if contact information provided)
* Announcement on official channels

#### Termination by You

You may terminate this license at any time by:

* Uninstalling the Software from all your devices
* Ceasing all use of the Software
* Deleting all copies of the Software in your possession or control

#### Effect of Termination

Upon termination of this license, whether automatic or otherwise:

* You must immediately cease all use of the Software
* You must uninstall the Software from all devices
* You must delete or destroy all copies of the Software in your possession
* You must delete all derivative works or modifications
* All rights granted under this license terminate immediately
* You remain liable for any breaches that occurred before termination

#### Survival

The following sections survive termination and remain in effect:

* Section 7 (Data Privacy and Responsibility)
* Section 8 (Attribution)
* Section 9 (Warranty Disclaimer)
* Section 10 (Limitation of Liability)
* Section 11 (Indemnification)
* Section 13 (Governing Law and Jurisdiction)
* Section 14 (Severability)
* Any other sections that by their nature should survive

### 13. GOVERNING LAW AND JURISDICTION

#### Governing Law

This license shall be governed by and construed in accordance with the laws of **Denmark**, without regard to its conflict of law principles.

#### Jurisdiction and Venue

Any legal action, suit, or proceeding arising out of or relating to this license or the Software shall be instituted exclusively in the courts of Denmark. You consent to the exclusive jurisdiction of such courts and waive any objection to venue.

#### Language

This license is drafted in English. Any translation is provided for convenience only. In the event of any conflict between the English version and any translation, the English version shall prevail.

#### Applicable Law

Danish law applies regardless of:

* Your location or residence
* Where the Software is used
* The location of any servers or infrastructure
* Conflict of law principles

#### International Use

If you use the Software outside Denmark, you are responsible for compliance with local laws and regulations in your jurisdiction.

### 14. SEVERABILITY

If any provision of this license is found to be unenforceable, invalid, or contrary to applicable law by a court of competent jurisdiction, that provision shall be:

* Limited or eliminated to the minimum extent necessary to make it enforceable
* Modified to reflect the parties' intent as closely as possible while remaining enforceable
* If modification is not possible, severed from this license

**Effect on Remaining Provisions:**

The remaining provisions of this license shall continue in full force and effect and shall not be affected by the invalidity or unenforceability of any other provision.

### 15. ENTIRE AGREEMENT

This license, together with the Privacy Policy and Terms of Service referenced herein, constitutes the entire agreement between you and Genesis Forge concerning the Software and supersedes all prior or contemporaneous:

* Agreements, whether oral or written
* Understandings
* Negotiations
* Representations
* Proposals
* Communications

**No Other Terms:**

No purchase order, acknowledgment, or other document shall modify or add to the terms of this license unless executed in writing by an authorized representative of Genesis Forge.

### 16. NO WAIVER

Failure by Genesis Forge to enforce any provision of this license, or to exercise any right or remedy available under this license, shall not constitute a waiver of:

* That provision
* That right or remedy
* Any other provisions, rights, or remedies

**No Single Waiver:** No single waiver shall constitute a continuing waiver of the same or any other provision.

**Written Waiver Required:** Any waiver must be in writing and signed by an authorized representative of Genesis Forge to be effective.

### 17. UPDATES AND MODIFICATIONS TO LICENSE

#### Right to Modify

Genesis Forge reserves the right to modify, amend, or update this license at any time, with or without notice, for any reason including but not limited to:

* Legal or regulatory changes
* Business considerations
* Improved clarity or protection
* New features or functionality
* Community feedback

#### Notice of Changes

When reasonably feasible, Genesis Forge will provide notice of material changes by:

* Displaying a notification within the Software
* Including information in release notes
* Posting on official website or repository
* Email notification (if contact information provided)

#### Effective Date

Modified license terms become effective:

* Immediately upon posting for new users
* 30 days after posting for existing users (for material changes)
* As otherwise specified in the modified license

#### Continued Use

Your continued use of the Software after license modifications constitutes acceptance of the new terms. If you do not agree to modified terms:

* You must cease using the Software
* You must uninstall the Software from all devices
* You must delete all copies in your possession

#### Version History

* Current license version number is displayed at the bottom of this document
* Previous versions may be available upon request by emailing edufocusbusiness@gmail.com
* Material changes will be documented in version notes

### 18. ASSIGNMENT

#### Your Assignment Rights

You may not assign, transfer, delegate, or sublicense this license or any rights or obligations hereunder, whether voluntarily, involuntarily, by operation of law, or otherwise, without the prior written consent of Genesis Forge.

**Prohibited Transfers:**
* Sale or transfer of the Software
* Transfer as part of asset sale
* Corporate merger or acquisition
* Inheritance or estate distribution
* Any other form of transfer

**Attempted Assignment:** Any attempted assignment in violation of this section is void and of no effect.

#### Genesis Forge Assignment Rights

Genesis Forge may freely assign, transfer, or delegate this license and any rights or obligations hereunder without restriction or your consent, including but not limited to:

* Corporate reorganizations
* Mergers or acquisitions
* Asset sales
* Transfers to affiliated entities
* Any other business purposes

### 19. FORCE MAJEURE

Genesis Forge shall not be liable for any delay or failure to perform any obligation under this license if such delay or failure results from causes beyond its reasonable control, including but not limited to:

**Natural Events:**
* Natural disasters (earthquakes, floods, hurricanes, etc.)
* Severe weather conditions
* Pandemics or epidemics
* Acts of God

**Human-Caused Events:**
* War, terrorism, or civil unrest
* Government actions, regulations, or orders
* Labor disputes or strikes
* Sabotage or vandalism

**Technical Events:**
* Internet service provider failures
* Power outages or utility failures
* Hardware or infrastructure failures
* Cyber attacks or security breaches
* Third-party service disruptions

**Effect:** Performance shall be excused during the period of such force majeure event. Genesis Forge will make reasonable efforts to mitigate effects and resume performance as soon as reasonably practicable.

### 20. THIRD-PARTY COMPONENTS

#### Open Source Components

The Software may include or incorporate third-party open-source software components. Such components are licensed under their respective open-source licenses, which may include:

* MIT License
* Apache License 2.0
* BSD Licenses
* Other permissive licenses

**Availability:** Complete license texts and attributions for third-party components are available:
* In the Software's "About" or "Licenses" section
* In accompanying documentation
* Upon request by emailing edufocusbusiness@gmail.com

#### Third-Party Rights

This license does not grant any rights in third-party components beyond those granted by their respective licenses. Users must comply with all applicable third-party licenses.

#### No Warranty for Third-Party Components

Genesis Forge provides no warranty, express or implied, for third-party components, which are provided "as is" under their respective licenses.

### 21. EXPORT COMPLIANCE

You agree to comply with all applicable export and import laws, regulations, and restrictions of the United States, the European Union, Denmark, and any other applicable jurisdiction.

**Prohibited Exports:**

You may not use, export, re-export, import, or transfer the Software:

* To any country, entity, or person subject to trade sanctions or embargoes
* In violation of any export control laws or regulations
* For any prohibited end-use (weapons development, nuclear activities, etc.)

**Representations:**

You represent and warrant that:

* You are not located in, under control of, or a national/resident of any prohibited country
* You are not on any government restricted party list
* You will not use the Software for any prohibited purpose
* You will comply with all applicable export control laws

### 22. GOVERNMENT USE

If you are a government entity or using the Software on behalf of a government:

**U.S. Government Rights:** The Software is a "commercial item" as defined in FAR 2.101, consisting of "commercial computer software" and "commercial computer software documentation" as used in FAR 12.212 and DFARS 227.7202. Government users acquire only those rights set forth in this license.

**Other Governments:** Similar restricted rights apply for other government users in accordance with applicable law.

### 23. NOTICES AND COMMUNICATIONS

#### To You

Genesis Forge may provide notices, announcements, or communications to you by:

* Displaying within the Software interface
* Email (if contact information voluntarily provided)
* Posting on official website or repository
* Including in release notes or documentation

#### To Genesis Forge

You may provide notices, questions, or communications to Genesis Forge by:

**Email:** edufocusbusiness@gmail.com

**Subject Lines:**
* "Legal Notice" - for legal communications
* "License Question" - for license inquiries
* "Commercial License" - for commercial licensing
* "Permission Request" - for permission requests
* "General Inquiry" - for other matters

**Physical Mail:** Available upon request for formal legal correspondence

**Response Time:** We aim to respond to all communications within 7-10 business days, though response times are not guaranteed.

### 24. INTERPRETATION

#### Headings

Section headings are for convenience only and shall not affect the interpretation of this license.

#### Language

* This license is drafted in English
* Any translations are provided for convenience only
* In case of conflict, the English version prevails

#### Definitions

* "Including" means "including but not limited to"
* Singular includes plural and vice versa
* "Or" is not exclusive (means "and/or")
* "May" indicates permission, not obligation
* "Shall" or "will" indicates obligation

#### Construction

This license shall not be construed more strictly against Genesis Forge as the drafter. Both parties have had opportunity to review and negotiate these terms.

### 25. CONTACT INFORMATION

**Genesis Forge**

**Primary Contact:**  
**Email:** edufocusbusiness@gmail.com

**For Inquiries Regarding:**

* **Commercial Licensing** - Subject: "Commercial License Inquiry"
* **Educational Institution Deployment** - Subject: "Educational Deployment"
* **Permission for Derivative Works** - Subject: "Permission Request"
* **License Questions or Clarifications** - Subject: "License Question"
* **Partnership Opportunities** - Subject: "Partnership Inquiry"
* **General Questions** - Subject: "General Inquiry"
* **Legal Matters** - Subject: "Legal Notice"
* **Bug Reports** - Subject: "Bug Report"
* **Feature Requests** - Subject: "Feature Request"

**Response Time:** We aim to respond within 7-10 business days.

**Business Hours:** Monday-Friday, 9:00 AM - 5:00 PM CET (Central European Time)

**Please Note:**
* We do not provide phone support
* All communications should be in English or Danish
* For fastest response, use clear and specific subject lines
* Include relevant details in your initial email

---

## ACCEPTANCE OF LICENSE TERMS

**BY INSTALLING, COPYING, ACCESSING, OR USING THE SOFTWARE, YOU ACKNOWLEDGE THAT:**

1. You have read this entire license agreement
2. You understand and agree to be bound by all terms and conditions
3. You have the legal capacity and authority to enter into this agreement
4. If entering into this agreement on behalf of an organization, you have authority to bind that organization
5. If you are under 18 years of age, your parent or legal guardian has reviewed and agreed to these terms on your behalf
6. You understand that the Software is provided "as is" without warranties
7. You understand and accept the limitations of liability set forth herein
8. You understand that Genesis Forge collects no user data and data is stored locally
9. You are responsible for backing up your data regularly
10. You will use the Software in compliance with all applicable laws and regulations

**IF YOU DO NOT AGREE TO THESE TERMS, DO NOT INSTALL, ACCESS, OR USE THE SOFTWARE.**

---

## ACKNOWLEDGMENTS

Genesis Forge thanks the following for their contributions to EduFocus Pro:

* **Open Source Community** - For invaluable open-source components
* **Translators** - For making EduFocus Pro accessible worldwide (credited in-app)
* **Beta Testers** - For testing and feedback
* **Users** - For bug reports, feature suggestions, and support

---

## VERSION INFORMATION

**License Version:** 2.0  
**Effective Date:** October 1, 2025  
**Last Updated:** October 5, 2025  
**Software Version:** 3.5.3

---

## QUICK REFERENCE SUMMARY

**THIS IS NOT A SUBSTITUTE FOR READING THE FULL LICENSE. THIS SUMMARY IS PROVIDED FOR CONVENIENCE ONLY.**

✅ **You MAY:**
- Use for personal study and education
- Install on multiple personal devices
- Modify for personal use only
- Use in educational institutions (free)
- Share official distribution links
- Back up your data

❌ **You MAY NOT:**
- Use commercially without a commercial license
- Distribute or sell the Software
- Share modified versions publicly
- Remove copyright or license notices
- Reverse engineer for competitive purposes
- Use the Software name for derivatives

⚠️ **Important:**
- No data collection by Genesis Forge
- Data stored locally on your device
- No warranties provided ("as is")
- Limited liability
- You must back up your own data
- Commercial use requires separate license

📧 **Contact:** edufocusbusiness@gmail.com

---

**Copyright © 2025 Genesis Forge. All Rights Reserved.**  
**EduFocus Pro - Privacy-First Education Technology**

**This is a legally binding license agreement. Please read carefully.**
